services:
  - type: web
    name: collabzz
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /(.*).html
        destination: /$1.html
      - type: rewrite
        source: /**
        destination: /index.html
